version: "2"

services:
  swarm_autoscale:
    container_name: swarm_autoscale
    image: node:8.11.1
    command: tail -f /dev/null
    working_dir: /var/app
    volumes:
      - ../src:/var/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEBUG=autoscale*